version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: atlas-postgres
    restart: always
    environment:
      POSTGRES_DB: atlas_db
      POSTGRES_USER: atlas_user
      POSTGRES_PASSWORD: atlas_password
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
