spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/atlas_db
    username: atlas_user
    password: atlas_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false
  jooq:
    sql-dialect: POSTGRES
  liquibase:
    change-log: classpath:/db/liquibase/db.changelog-master.yaml
    enabled: true

server:
  port: 8080
