spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shop_db
    username: shop_user
    password: shop_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false
  jooq:
    sql-dialect: POSTGRES

server:
  port: 8080
